### ISSUE TITLE
系統應該自動登出

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#32]
我們可以大致上定一個時間
例如三小時後 如果他沒有active 系統就自動登出

**Comment by hsiaoball** [comment]
不過Facebook, linkedin也是一直login 需要登出的理由是?

On Mon, Sep 29, 2014 at 11:44 PM, yuchien007 notifications@github.com
wrote:

> 我們可以大致上定一個時間
> 例如三小時後 如果他沒有active 系統就自動登出
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hsiaoball/renmo/issues/32.

## 

Chi-Yo Hsiao (Leo)
蕭啟佑

**Comment by yuchien007** [comment]
這樣會不會有security的問題
不過你說的也對
只是我剛沒意料到我一開 他會幫我登入cc
這個你決定吧

如果你覺得不必要就關掉issue
