### ISSUE TITLE
fb like and share

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#36]
can yo move this to the pink bar down below?
where you have the "aa
![screen shot 2014-09-30 at 11 34 24 am](https://cloud.githubusercontent.com/assets/8952268/4464077/b338e106-48d0-11e4-97d5-3296518d6364.png)
"

**Comment by hsiaoball** [comment]
but this one is independent for each post. and the aa bottom section if
shared for all over the site

On Tue, Sep 30, 2014 at 11:36 AM, yuchien007 notifications@github.com
wrote:

> can yo move this to the pink bar down below?
> where you have the "aa
> [image: screen shot 2014-09-30 at 11 34 24 am]
> https://cloud.githubusercontent.com/assets/8952268/4464077/b338e106-48d0-11e4-97d5-3296518d6364.png
> "
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hsiaoball/renmo/issues/36.

## 

Chi-Yo Hsiao (Leo)
蕭啟佑

**Comment by yuchien007** [comment]
喔喔 我以為你是要share FUNZZ的意思
我個人覺得現在放在這裡好像是個bug....
我可能得再找找位置放, 但是demo前不知道有沒有空

**Comment by hsiaoball** [comment]
我先把他移掉吧

**Comment by yuchien007** [comment]
ok. I will close this issue
