### ISSUE TITLE
Mouse over Feature Post

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#41]
mouse over each feature post should show info like this
![screen shot 2014-09-28 at 4 36 44 pm](https://cloud.githubusercontent.com/assets/8952268/4465386/2397fd06-48db-11e4-9d93-56ae2f7e899b.png)

**Comment by hsiaoball** [comment]
如果poster沒登入 或是user沒登入 要怎麼顯示connection?

**Comment by yuchien007** [comment]
我覺得那就把connection的地方拿掉
其他rent, available date and location 往上移 變成在框框中間

你覺得呢？
我想了一下 如果在小框框還要寫說login to see your connection可能有點太擠
然後每個框框都出現重複的訊息有點煩

**Comment by yuchien007** [comment]
great job! 
每行間距要加大一點
大約是現在的1.5倍
謝啦！！

**Comment by yuchien007** [comment]
sorry 再改一次 我覺得還不夠...
line-height: 130%;
font-size: 130%;

**Comment by yuchien007** [comment]
可以修一下這個嗎
在event 4
![screen shot 2014-10-02 at 1 03 15 pm](https://cloud.githubusercontent.com/assets/8952268/4497462/49fc079a-4a6f-11e4-96e4-5b909a2f82d3.png)

**Comment by yuchien007** [comment]
這個有修好嗎
我還是沒看到 
他現在顯示的還是跟我貼的圖一樣
