### ISSUE TITLE
Center Profile Pic 

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#43]
他好像沒有截取我照片的中間？
這可能不是bug 可是你可以研究看看嗎
不知道是我照片的問題
還是說他系統抓照片的設定不對
![screen shot 2014-09-30 at 1 02 48 pm](https://cloud.githubusercontent.com/assets/8952268/4465591/e6e6c8e0-48dc-11e4-82c1-98ff7b9e371e.png)

**Comment by hsiaoball** [comment]
你可以po一篇 或是在哪一篇回個文嗎? gave a recommadtion on a post. 然後我才可以看到 去做更改

**Comment by yuchien007** [comment]
I tried to post on event 4 and 3 but I couldn't
I typed something and hit comment but nothing happened

Maybe you can create a funzzi facebook account and we can use it for testing. it would be more efficient this way rather than waiting me to test it for you.

**Comment by hsiaoball** [comment]
I think this depend on the profile pic. The default setting is taking middle of the pic. I have fix the commend function. Please try again

**Comment by yuchien007** [comment]
i posted on event 8. can u still test the profile pic when u get a chance?

![screen shot 2014-10-01 at 5 55 02 pm](https://cloud.githubusercontent.com/assets/8952268/4485594/ce3bc5f0-49ce-11e4-9998-c065a302221c.png)

**Comment by hsiaoball** [comment]
我覺得他應該是用你FB的照片去截 因為你這張比較長 所以截中間的時候蓋到眼睛 還是我們要統一都往上截一點?

**Comment by yuchien007** [comment]
好啊 這個好像是一個大任務
我還得研究大家的fb profile pic都長啥樣子
但是我記得我跟julie的都很類似
如果不難改的話 你先把他往上截好了
這樣demo也好看一點
我再來看看其他範本

**Comment by hsiaoball** [comment]
我先往上15%
