### ISSUE TITLE
調整大小卡search button 

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#48]
![screen shot 2014-10-01 at 1 25 47 pm](https://cloud.githubusercontent.com/assets/8952268/4482514/500ba170-49a9-11e4-8c52-a008585d5c6b.png)
現在這個白色的button 把它調整跟其他兩個searchbox同高
寬度與放大鏡icon的大小 比例大概跟下圖一樣
透明度調整成 90％

[放大鏡icon比例如下圖]
![screen shot 2014-10-01 at 1 30 09 pm](https://cloud.githubusercontent.com/assets/8952268/4482565/d3c42c80-49a9-11e4-9a23-79e0d0f870d5.png)

**Comment by yuchien007** [comment]
你有調透明度嗎
我看不出來
如果有的話在加大
顏色跟右邊searchbox的mm/dd/yyyy一樣

**Comment by hsiaoball** [comment]
改了 晚點上傳

**Comment by yuchien007** [comment]
你有改button的形狀嗎
把它改成長方形
比例跟我上面給你的藍色search button一樣

**Comment by hsiaoball** [comment]
改好了 
BTw 下次可以直接給我長度 in px嗎? 這樣比較好條 :+1:

**Comment by yuchien007** [comment]
okok 但是如果我給你一個fix size
那不會有responsive的問題嗎？

**Comment by hsiaoball** [comment]
先用fix吧  之後要改responsive在一起改

On Thu, Oct 2, 2014 at 1:31 PM, Alicia notifications@github.com wrote:

> okok 但是如果我給你一個fix size
> 那不會有responsive的問題嗎？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hsiaoball/renmo/issues/48#issuecomment-57700159.

## 

Chi-Yo Hsiao (Leo)
蕭啟佑

**Comment by yuchien007** [comment]
ok!
