### ISSUE TITLE
小卡scroll bar

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#49]
現在看上去小卡會有兩個scroll bar
你讓小卡的scroll bar only show on mouse over
like this website
http://www.gq.com.tw/business/preview.asp?ids=5&cid=27

[問題]
scroll bar的樣子可以調整嗎
我想把它弄得比較不明顯一點
因為我們現在data太少
scroll bar整個會很長一條很明顯 不太好看

**Comment by hsiaoball** [comment]
可以調整了 在跟我說要長得怎麼樣子
