### ISSUE TITLE
Share Bath Icon on Big Card

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#52]
我個人有個想法
如果bath是share的話 就不應該show icon
因為share bath不是好feature, 不應該強調
所以我覺得那個bath icon will only shown when it's a private bath

[event1]
![screen shot 2014-10-02 at 10 16 27 am](https://cloud.githubusercontent.com/assets/8952268/4495101/1d17c140-4a58-11e4-8fb6-7190bbff2720.png)

**Comment by yuchien007** [comment]
我不知道你這個邏輯有沒有改對
首先private bath要在出租一個房間的情況下才會出現
如果是租整棟 就不用顯示這個
根據我們之前的討論
rooms for rent裡面要有說有bath才是private bath的意思
我剛看了幾篇post都沒有看到這樣寫
可是上面卻有icon 我覺得好像不是很正確

**Comment by hsiaoball** [comment]
今晚可能要來討論一下

**Comment by yuchien007** [comment]
icon方便我不知道你update了沒
我們討論的結果是最多show 4個icon
而且這四個icon文字都是固定 for example: share bath or private bath都要show
只要user有填資料就要show icon
