### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#56]
let's be consistent with the date format
所有關於日期的都用這個型式 "Mar 15, 2014"
把月份拼出來 因為有些國家會把date寫在前面
變成dd/mm/year 這樣有些user會不知道哪個是月哪個是date
所以我們都會用文字表示月份

![screen shot 2014-10-02 at 1 51 21 pm](https://cloud.githubusercontent.com/assets/8952268/4498175/55342cc6-4a76-11e4-8b9c-fd8e1e18e37f.png)

**Comment by hsiaoball** [comment]
the input of date can't be changed.
fixed other place
