### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#61]
dropbox (design>assets>logo) 裡面有放了幾個logo
你可以選你喜歡的試試看

我後來用拼圖的概念做了一些
因為我覺得我們的網站很像在灣區拼湊一張大拼圖
把所有住戶都連接起來

你也可以再給我一些logo的feedback
做logo真的就不是我本行了...
需要多點點子激發一下

**Comment by hsiaoball** [comment]
我很喜歡拼圖的概念 Good idea!
我現在最喜歡8
想說因為是房子 不要歪一邊比較好
然後我想說可以讓圖片裡的白色房子往上移出頭
像是另一個卡榫
也有出頭天的感覺 :)

**Comment by yuchien007** [comment]
我還不太懂你的意思 我們今天可以一起弄一下

**Comment by yuchien007** [comment]
logo放到db了
麻煩update
file name:
1withshadow.png

**Comment by yuchien007** [comment]
我覺得這個logo現在看起來給人家一種沒有滾到頁面最上面的feel
會讓人家忍不住一直想往上scroll
還有陰影沒處理好
我之後做好給你再把issue assign to you

**Comment by yuchien007** [comment]
麻煩把logo換成8.png 這張圖
