### ISSUE TITLE
Add connection icon in small card and home page

### ISSUE THREAD

**Issue by yuchien007** [hsiaoball/Funzzi#63]
icons are in dropbox: design > assets > icons > connections

For feature post 
- icon用53%透明度
- 在每個feature的右上角
  像這個圖
  ![screen shot 2014-10-03 at 7 29 39 pm](https://cloud.githubusercontent.com/assets/8952268/4514438/59887e64-4b6e-11e4-87e3-6ca2a411e180.png)

For small card:
- 不要做透明
- 把現有的粉紅色圈拿掉 用這些icon取代

0 connection 的我們先放0, demo完看大家的feedback

**Comment by yuchien007** [comment]
這個小卡的icon我直接給你好了
我想把它改粉紅色
透明的地方變白色

**Comment by hsiaoball** [comment]
我改好feature post了
不過要不要讓Hi明顯一點? 換成不同顏色或調整亮度?

**Comment by yuchien007** [comment]
update一下icon, 已經放到dropbox了
大卡用粉紅色的icon
home page用黑色的icon ＊＊改成不透明
